{% set name = "pylodstorage" %}
{% set version = "0.18.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylodstorage-{{ version }}.tar.gz
  sha256: 7e993a4a148aa2c37c17bf5e558a5c17369dec1ceed06cf4a01ee856851ec82d

build:
  entry_points:
    - sparqlquery = lodstorage.querymain:mainSPARQL
    - sqlquery=lodstorage.querymain:mainSQL
    - lodquery=lodstorage.querymain:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - hatchling
  run:
    - dacite
    - dataclasses-json
    - dicttoxml2
    - jsonpickle >=4.0.2
    - matplotlib-base
    - numpy
    - owlready2
    - orjson
    - pandas
    - pybasemkit
    - pygments
    - pymysql
    - python >={{ python_min }}
    - python-slugify
    - pyyaml
    - ratelimit
    - requests
    - sparqlwrapper
    - tabulate

test:
  imports:
    - lodstorage
    - sampledata
  commands:
    # Remove this once dacite fixes its dependency mess
    - pip install --upgrade dacite
    - pip check
    - sparqlquery --help
    - sqlquery --help
    - lodquery --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WolfgangFahl/pyLodStorage
  summary: python List of Dict (Table) Storage library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cml37
