{% set name = "pylodstorage" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylodstorage-{{ version }}.tar.gz
  sha256: c865b565d590fb9be33dc14797f9ec2c931045d010a942f028ed0252ed090314

build:
  entry_points:
    - sparqlquery = lodstorage.querymain:mainSPARQL
    - sqlquery=lodstorage.querymain:mainSQL
    - lodquery=lodstorage.querymain:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - hatchling
  run:
    - dacite
    - dataclasses-json
    - dicttoxml2
    - jsonpickle
    - matplotlib-base
    - numpy
    - orjson
    - pandas
    - pygments
    - pymysql
    - python >={{ python_min }}
    - python-slugify
    - pyyaml
    - ratelimit
    - requests
    - sparqlwrapper
    - tabulate

test:
  imports:
    - lodstorage
    - sampledata
  commands:
    - pip check
    - sparqlquery --help
    - sqlquery --help
    - lodquery --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WolfgangFahl/pyLodStorage
  summary: python List of Dict (Table) Storage library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cml37
