{% set name = "pylodstorage" %}
{% set version = "0.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pylodstorage-{{ version }}.tar.gz
  sha256: b549629651f2fc63c6a7ed94088c41679ff14478d4ce6cf76082995d67fdb1f4

build:
  entry_points:
    - sparqlquery = lodstorage.querymain:mainSPARQL
    - sqlquery=lodstorage.querymain:mainSQL
    - lodquery=lodstorage.querymain:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - hatchling
  run:
    - dacite
    - dataclasses-json
    - dicttoxml2
    - jsonpickle >=4.0.2
    - matplotlib-base
    - numpy
    - owlready2
    - orjson
    - pandas
    - pygments
    - pymysql
    - python >={{ python_min }}
    - python-slugify
    - pyyaml
    - ratelimit
    - requests
    - sparqlwrapper
    - tabulate

test:
  imports:
    - lodstorage
    - sampledata
  commands:
    - pip check
    - sparqlquery --help
    - sqlquery --help
    - lodquery --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WolfgangFahl/pyLodStorage
  summary: python List of Dict (Table) Storage library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cml37
